server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: buy-books
  datasource:
    url: jdbc:postgresql://localhost:5432/buy-books-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: info
    org.springframework: info

wc:
  api:
    base-url-wp:          "https://buy-books.com.ua/wp-json/wp/v2"
    base-url-woocommerce: "https://buy-books.com.ua/wp-json/wc/v3"
    consumer-key: "${WC_API_KEY}"
    consumer-secret: "${WC_API_SECRET}"

wp:
  admin:
    username: "${WP_ADMIN_USERNAME}"
    app-password: "${WP_ADMIN_APP_PASSWORD}"

scheduler:
  import-enabled: false